#   AED  - Curso  2003/2004 -  UM
#   David      Perez      Cabrera
#   Miguel Angel Orenes Fernandez 
#   Buscador   de   paginas   web
#   Version 1.0
#
#   profesor:
#            Norberto Marin Perez

Buscador: principal.cpp
	c++ -o Buscador principal.cpp

#  $Id: makefile
#  v 1.0 30/07/2004 18:51:30
#  David Perez Cabrera
	  
